apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-1
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/acainelli/nuke-argocd.git
    targetRevision: HEAD
    path: apps
    helm:
      releaseName: root-app-1
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
