apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-1
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/helm/examples.git
    targetRevision: main
    path: charts/hello-world
    helm:
      releaseName: app-1
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
