apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: parent-apps
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
    applicationsSync: create-update
  generators:
    - git:
        directories:
          - path: apps/hello-world-app-1
          - path: apps/hello-world-app-2
        repoURL: https://github.com/acainelli/nuke-argocd.git
        requeueAfterSeconds: 20
        revision: HEAD
  template:
    metadata:
      name: "{{`{{path.basename}}`}}"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/acainelli/nuke-argocd.git
        targetRevision: HEAD
        path: "{{`{{path}}`}}"
        helm:
          releaseName: "{{`{{path.basename}}`}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=false
          - PruneLast=false
